[package]
name = "rust_codes"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
path = "binary_search_insertion_index/src/lib.rs"

[[bin]]
name = "binary_search_insertion_index"
path = "binary_search_insertion_index/src/lib.rs"
